# cluster-k8s\Ipingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ip-ingress
  # namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
      - hosts:
          - innova-path.com
          - www.innova-path.com
        secretName: innova-path-tls
  rules:
    - host: innova-path.com
      http:
        paths:         
          - path: /api
            pathType: Prefix   
            backend:
              service:
                name: backend-service
                port:
                  number: 80          
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip-frontend-service
                port:
                  number: 80         
    - host: www.innova-path.com
      http:
        paths:         
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 80         
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ip-frontend-service
                port:
                  number: 80           